### ISSUE TITLE
expose server side analytics

### ISSUE THREAD

**Issue by jab** [readthedocs/readthedocs.org#5141]
As of #4131, it looks like Read the Docs is tracking some analytics server side. Awesome: This offers advantages to documentation readers (e.g. their IPs are anonymized before being sent to Google Analytics), but also an advantage to documentation *publishers* that is not yet realized: Currently publishers need to supply their own Google Analytics tracking ID to be able to track views of their docs, which (1) not all publishers bother to do (it's buried under Advanced Settings), and (2) won't count visitors who block requests to GA (e.g. using a browser extension). If Read the Docs exposed to projects the server side analytics that it's already tracking, it would address both these issues. Surfacing even just one or two metrics such as visitors per month and pageviews per month would be really useful. Any interest?

Thanks for your consideration and for all your work on Read the Docs!

**Comment by jab** [comment]
Thanks for the quick reply @davidfischer, and glad to hear this is already on your radar! One quick followup thought: I know Cloudflare is able to do this for its users and makes the data available via its [API](https://api.cloudflare.com/#zone-analytics-dashboard) as well as its browser UI. Here's a screenshot I just took for one of my sites:

![screen shot 2019-01-21 at 17 34 28](https://user-images.githubusercontent.com/64992/51502191-fabb5800-1da2-11e9-94aa-7cbc1c7b330e.png)

It looks like Read the Docs is using Azure CDN, which I've no experience with, but maybe they provide something similar that could save you some work?

**Comment by davidfischer** [comment]
Currently we are only using Azure CDN for static files and not for dynamic content so I don't think it would work in its current form.

Secondly, we attach a lot of data to pageviews and events so we can understand the site better. For example, I look at pageviews by programming language of the docs or pageviews by Sphinx theme pretty frequently. Ideally I'd like to still get that.

Interestingly, the really privacy conscious stuff in GA is the stuff I don't want or need at all. I don't need any demographics info and I don't need to know that a user who visited our site 6 months ago is "returning".

**Comment by davidfischer** [comment]
<img width="1108" alt="screen shot 2019-01-21 at 2 55 11 pm" src="https://user-images.githubusercontent.com/185043/51502823-b7ee8580-1d8c-11e9-9c95-356322370355.png">

Just to show off, here's a small dashboard of custom dimension breakdowns. It's a week's worth of data. I removed stuff that would identify single projects or small groups.

**Comment by stsewd** [comment]
@davidfischer was this solved by https://github.com/readthedocs/readthedocs.org/pull/6121?

**Comment by davidfischer** [comment]
It isn't quite exactly the same but it is partially solved. It's probably good enough to call it done.
