### ISSUE TITLE
Command killed due to excessive memory consumption (despite minimum dependencies)

### ISSUE THREAD

**Issue by DominiqueMakowski** [readthedocs/readthedocs.org#6692]
## Details

* https://github.com/neuropsychology/NeuroKit
* https://readthedocs.org/projects/neurokit2/builds/10491079/
* RTD username: DominiqueMakowski

It fails with `Collecting package metadata (repodata.json): ...working... Killed   Command killed due to excessive memory consumption`

My [environment.yml](https://github.com/neuropsychology/NeuroKit/blob/master/docs/environment.yml) looks like follows:

```
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - sphinx>=1.4
  - pip
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - nbsphinx
```

Thanks for your help ☺️

**Comment by st-bender** [comment]
Hi there,
Using
```yaml
image: stable
```
fixed it for me.

**Comment by DominiqueMakowski** [comment]
@st-bender unfortunately, it seems that this trick didn't fix the problem for us:

https://github.com/neuropsychology/NeuroKit/blob/2dca06dcdbe7d530214c6267b0bd10d74dada8e4/readthedocs.yml#L1-L3

result: https://readthedocs.org/projects/neurokit2/builds/10507712/

**Comment by st-bender** [comment]
> @st-bender unfortunately, it seems that this trick didn't fix the problem for us:
> 
> https://github.com/neuropsychology/NeuroKit/blob/2dca06dcdbe7d530214c6267b0bd10d74dada8e4/readthedocs.yml#L1-L3
> 
> result: https://readthedocs.org/projects/neurokit2/builds/10507712/

Hi,
sorry to hear that, but I believe you modified the wrong file. That's probably my mistake, the `image` has to be inside a `build` section of `readthedocs.yml` **not** the `environment.yaml` for conda. Mine looks like this:
```yaml
# readthedocs.yml
build:
  image: stable
conda:
  file: .rtd-environment.yml
python:
    setup_py_install: true
    version: 3.6
```

**Comment by DominiqueMakowski** [comment]
Yup, that's what I realised, thanks a lot for the details! 

But unfortunately, still fails 😞

**Comment by st-bender** [comment]
> Yup, that's what I realised, thanks a lot for the details!
> 
> But unfortunately, still fails

Sorry to hear that, but I see that it got a few steps further, it no longer stops at `conda create ...`. I am not sure if you need the last lines with the `python` section though (they are in my file to install the package). If you didn't need them before it's probably safe to remove them.

**Comment by stsewd** [comment]
@DominiqueMakowski make sure you use the latest version of the configuration file https://docs.readthedocs.io/en/stable/config-file/v2.html

Also, changing to the stable image may fix your problem. We released new images with the latest version of conda, which seem to be using more memory than before. Try checking https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html. If nothing of that works, we can help you increasing the build resources for your project.

**Comment by DominiqueMakowski** [comment]
@stsewd I tried every combination but it is still throw the same error. How can we try increasing the resources?

**Comment by stsewd** [comment]
@DominiqueMakowski I have increased the build resources for your project, but it's failling for another reason https://readthedocs.org/projects/neurokit2/builds/10515329/

**Comment by DominiqueMakowski** [comment]
@stsewd Thanks a lot for your feedback! I have fixed the other reason (https://github.com/neuropsychology/NeuroKit/pull/137), but it's back again with the memory error (https://readthedocs.org/projects/neurokit2/builds/10525593/)

**Comment by stsewd** [comment]
@DominiqueMakowski I have increased the resources, but it's still falling with the previous error, I tried dev and latest https://readthedocs.org/projects/neurokit2/builds/10558611/ https://readthedocs.org/projects/neurokit2/builds/10558703/

**Comment by DominiqueMakowski** [comment]
This got fixed after increasing the resources, thanks a lot!
