### ISSUE TITLE
Can't delete my account, probably because I've change username on github 

### ISSUE THREAD

**Issue by applicato** [readthedocs/readthedocs.org#6753]
## Details

* Build URL (if applicable): 
https://readthedocs.org/accounts/delete/
* Read the Docs username (if applicable): 
botessa

## Expected Result 
deleted account

## Actual Result
    .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!

*A description of what actually happened*
idn

**Comment by stsewd** [comment]
Sorry about that, that's a bug from one of our dependencies that broke when we upgraded to django 2.2

A fix was merged, but isn't released yet https://github.com/AliLozano/django-messages-extends/pull/26

**Comment by stsewd** [comment]
The fix will be available next Tuesday

**Comment by alex1a** [comment]
Same issue here, but instead i change my github account, i delete my primary email

**Comment by stsewd** [comment]
This should have been fixed in the last release https://github.com/readthedocs/readthedocs.org/pull/6767

@applicato are you able to delete your account now?

@alex1a are you experimenting this now?

**Comment by stsewd** [comment]
Sorry everyone, turns out the bug was still present. But it's fixed now https://github.com/readthedocs/readthedocs.org/pull/6817. You should be able to delete your account.

**Comment by binkoni** [comment]
I tried to delete my account, but still fails with a message "Fail.  Check back in a bit!"

**Comment by stsewd** [comment]
I just tested this, I was able to delete an account. But I can see another related bug to this on sentry, not sure what produced it.

**Comment by stsewd** [comment]
@binkoni I can see you are the only user experimenting this so far, looks like something happened on the db... I did a small change to test something. Can you please try deleting your account again?

**Comment by HGladiator** [comment]
it still fails with a message "Fail. Check back in a bit!"

**Comment by stsewd** [comment]
Hi again everyone, we found and fixed the second bug. You should be able to delete your accounts now.

**Comment by alex1a** [comment]
> 
> 
> This should have been fixed in the last release #6767
> 
> @applicato are you able to delete your account now?
> 
> @alex1a are you experimenting this now?

Today i try to delete my secondary account and receive this successful message: "You have successfully deleted your account". Thank you @stsewd for the support
