### ISSUE TITLE
repository import filter doesn't

### ISSUE THREAD

**Issue by cjw296** [readthedocs/readthedocs.org#7572]
## Details

I'm trying to add a project (cjw296/giterator), so selected just cjw296

<img width="853" alt="Screenshot 2020-10-19 at 08 23 43" src="https://user-images.githubusercontent.com/632049/96414022-7189bd00-11e4-11eb-903e-b7870b604f1a.png">

## Expected Result

Only cj296 projects to be shown.

## Actual Result

A mish-mash of projects.

As a feature request related to this, it would be great to be able to search for a repo on this screen. conda-forge is impossible to navigate by paging through...

**Comment by humitos** [comment]
> I'm trying to add a project (cjw296/giterator),

Is this project new? You may need to hit the 2 circle arrows to refresh your repositories. This may be automatic in a near future, but for now it's a manual action the user as to take.

> As a feature request related to this, it would be great to be able to search for a repo on this screen. conda-forge is impossible to navigate by paging through...

We are working on this already. We hope to have it deployed sooner than later.

**Comment by cjw296** [comment]
I don't think the project being new or not affects selecting `cjw296` and not actually having the returned results filtered to be just from that org/user, no?

**Comment by humitos** [comment]
Oh! Yes, I misread the issue description, sorry. We had a bug some weeks/months ago regarding repositories not being properly linked to organizations. Have you tried hitting the refresh button? That may fix this issue as well.

**Comment by cjw296** [comment]
It's better, but https://github.com/liamg/aminal still appears when I filter to `cjw296`, something to do with orgs vs people perhaps? All "people" repos I have access to getting lumped into one category?
Also weirdly: there are two "Pylons Project" entries on the right filter nav, one of them filters down to nothing when I click on it.

**Comment by humitos** [comment]
> It's better, but [liamg/aminal](https://github.com/liamg/aminal) still appears when I filter to `cjw296`, something to do with orgs vs people perhaps? All "people" repos I have access to getting lumped into one category?

This is correct. If you have access to a repository directly (not through an organization) they appear under your username's filter.

> Also weirdly: there are two "Pylons Project" entries on the right filter nav, one of them filters down to nothing when I click on it.

This looks like a bug. What's your username on Read the Docs?

**Comment by cjw296** [comment]
> This is correct. If you have access to a repository directly (not through an organization) they appear under your username's filter.

That's not a great experience, tbh...


> This looks like a bug. What's your username on Read the Docs?

chris@python.org

**Comment by humitos** [comment]
> > This is correct. If you have access to a repository directly (not through an organization) they appear under your username's filter.
> 
> That's not a great experience, tbh...

Under which filter these repositories should appear to make it better?

**Comment by cjw296** [comment]
> Under which filter these repositories should appear to make it better?

Taking `liamg/aminal` as an example, I would expect there to be a `liamg` filter in the "filter repositories" list, and I would expect it to appear there.

**Comment by stsewd** [comment]
@cjw296 are you still seeing the duplicate entries for "Pylon projects"? The other problem you mention is going to be fixed with https://github.com/readthedocs/readthedocs.org/issues/7509

**Comment by cjw296** [comment]
Yep, see attached image.
<img width="305" alt="Screenshot 2020-12-18 at 10 13 57" src="https://user-images.githubusercontent.com/632049/102602699-ca5ccf80-4119-11eb-91ca-c93e32ee028c.png">

**Comment by humitos** [comment]
This issue is going to be resolved once we finish with the `RemoteRepository` db normalization. We are working on this in this branch already https://github.com/readthedocs/readthedocs.org/tree/remote-repository-normalization

**Comment by humitos** [comment]
@cjw296 we deploy a fix yesterday. Can you confirm this is fixed for you and close this issue?

**Comment by cjw296** [comment]
The duplicate entries for "Pylon projects" are gone, but https://github.com/liamg/aminal still appears when I filter to `cjw296` but I'll follow #7509 for that.

Thanks for fixing this!
