### ISSUE TITLE
Error 502 when deleting a project

### ISSUE THREAD

**Issue by mn-mikke** [readthedocs/readthedocs.org#7882]
When I try to delete a project I get the error 502:

<img width="940" alt="Screen Shot 2021-01-29 at 11 56 19" src="https://user-images.githubusercontent.com/3674621/106266867-3ce8c100-6229-11eb-8f4a-c105c010a431.png">

**Comment by humitos** [comment]
This is known problem and we are working on a solution (on a private repository: https://github.com/readthedocs/readthedocs-ext/pull/399) that will be deployed in the next release. We are working on some operation tasks and that's why we haven't deployed it yet.

The problem is that we are hitting some CF APIs when the project is deleted, and that request is taking more time that it should.

**Comment by pope1ni** [comment]
The same error occurs when trying to delete an account which has a project that cannot be deleted.

**Comment by stsewd** [comment]
> The same error occurs when trying to delete an account which has a project that cannot be deleted.
> 
> I found that the issue occurred where the project had a large number of inactive versions listed.

thanks for that info, I think we should only purge active versions being deleted.

**Comment by pope1ni** [comment]
I presume this is now fixed and can be closed? (I was able to delete a project that was previously failing to delete.)

**Comment by humitos** [comment]
No. We still have a problem that we are hitting Cloudflare and it sometimes fails with Timeout. We need to move that call to a Celery task.

**Comment by pope1ni** [comment]
> No. We still have a problem that we are hitting Cloudflare and it sometimes fails with Timeout. We need to move that call to a Celery task.

Ah, ok. I was just following up that my situation seems to have been resolved and was just checking that this issue wasn't left behind. I'll unsubscribe now, but wish you best in following this through.

**Comment by humitos** [comment]
We already deploy a solution for this. I'm closing this issue.
