### ISSUE TITLE
many older doc versions have broken JS

### ISSUE THREAD

**Issue by leos** [readthedocs/readthedocs.org#8323]
## Details

* Read the Docs project URL: https://django-reversion.readthedocs.io/en/release-1.8/

## Expected Result

Clicking on the version selector down in the bottom left should work. It should pop up a selector that lets me pick a version of the docs.

## Actual Result

Clicking on it doesn't do anything and there's an error in the console:
```
(index):383 Uncaught ReferenceError: SphinxRtdTheme is not defined
    at HTMLDocument.<anonymous> ((index):383)
    at f (jquery-2.0.3.min.js:23)
    at Object.fireWith [as resolveWith] (jquery-2.0.3.min.js:23)
    at Function.ready (jquery-2.0.3.min.js:22)
    at HTMLDocument.dt (jquery-2.0.3.min.js:22)
(anonymous) @ (index):383
f @ jquery-2.0.3.min.js:23
fireWith @ jquery-2.0.3.min.js:23
ready @ jquery-2.0.3.min.js:22
dt @ jquery-2.0.3.min.js:22
readthedocs-doc-embed.js:1
Applying theme sidebar fix...
```

This appears to happen on old versions of docs for multiple projects that I tried. Happy to provide a few more if it's helpful. On https://django-reversion.readthedocs.io/en/latest/ the popup works correctly, but switching to one of the older versions breaks it.

**Comment by humitos** [comment]
Thanks for the report!

We have this chunk of JS embeded in the HTML:

```html
  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.StickyNav.enable();
      });
  </script>
```

`SphinxRtdTheme` is defined in https://media.readthedocs.org/javascript/readthedocs-doc-embed.js --which is loaded by the page, but it seems it is loaded _after_ this code is executed.

**Comment by stsewd** [comment]
This is coming from the theme https://github.com/readthedocs/sphinx_rtd_theme/blob/8a026194285971d25fa80d47bc1a703b4d67f60d/sphinx_rtd_theme/layout.html#L228-L232

but I don't see anything being loaded async or in the wrong order

```html
  <script type="text/javascript" src="https://media.readthedocs.org/javascript/readthedocs-doc-embed.js"></script>
  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.StickyNav.enable();
      });
  </script>
```

The only thing that could have made this happen would be if window is undefined.... which would be weird, I think?

https://github.com/readthedocs/sphinx_rtd_theme/blob/8a026194285971d25fa80d47bc1a703b4d67f60d/src/theme.js#L227-L235

**Comment by stsewd** [comment]
> The only thing that could have made this happen would be if window is undefined.... which would be weird, I think?

Looks like it's defined, so more like a race condition with the other part of the script being loaded before... but I don't understand how that would be possible with the current order

**Comment by astrojuanlu** [comment]
Found in other projects as well, for example https://neuropsydia.readthedocs.io/

**Comment by benjaoming** [comment]
Another example: https://django-tenant-schemas.readthedocs.io/

It's weird. When the jQuery block is executed, `SphinxRtdTheme` is not defined and it fails. After loading the document, `SphinxRtdTheme` is defined. But calling `SphinxRtdTheme.StickyNav.enable()` doesn't make the Flyout menu work.

**Comment by kuzmoyev** [comment]
Same issue with the search page (e.x. [gcsa](https://google-calendar-simple-api.readthedocs.io/en/latest/search.html?q=SendUpdatesMode&check_keywords=yes&area=default))

**Comment by benjaoming** [comment]
@kuzmoyev thanks for adding feedback here - this project is broken because it uses Sphinx 6.x and hasn't upgraded to sphinx-rtd-theme 1.2.0. If you can contribute a fix to them, that'd be great :+1:

**Comment by kuzmoyev** [comment]
Thanks for the info. I'm the owner of the project. I don't have a cap on the `sphinx` and `sphinx-rtd-theme` versions, but for some reason, the last build was with `sphinx-rtd-theme=0.5.1`. Hitting rebuild resolved the issue

**Comment by benjaoming** [comment]
@kuzmoyev haha, that makes it very easy for you to contribute to the project :100: thanks for confirming that it works, I guess the former build from last week happened exactly _before_ sphinx-rtd-theme 1.2.0 was released.

**Comment by spacemanspiff2007** [comment]
I'm experiencing the same issue for [sml2mqtt](https://sml2mqtt.readthedocs.io/en/rework/index.html) when building with `sphinx_rtd_theme 1.2.0` and `sphinx 6.1.3`

**Comment by benjaoming** [comment]
Hi @spacemanspiff2007 - thanks for reporting. Looking at your build configuration, I didn't find anything problematic.

In the HTML output[1], it appears that jquery.js has been included as the *last* file instead of the *first*. This is opposite behavior from before. I'll have to look into why that has happened.

[1] ``view-source:https://sml2mqtt.readthedocs.io/en/rework/index.html``

**Comment by spacemanspiff2007** [comment]
The last build from ~14 days ago worked fine so it seems there was something introduced in that time frame.

**Comment by benjaoming** [comment]
@mgeier it's the same symptom as https://github.com/readthedocs/readthedocs.org/issues/8323#issuecomment-1374890632 describes. I can't see anything in the served JS that has changed, and the HTML is untouched (static). I think the issue might be browser-related. It's pretty hard to fix in this case. If anyone has access to an older browser, could be worth seeing how it works there..

**Comment by mgeier** [comment]
>  I think the issue might be browser-related.

Is there a browser where it is known to work?

In all browsers I tried it consistently didn't work.

> If anyone has access to an older browser, could be worth seeing how it works there..

How old are you talking?

I tried https://nbsphinx.readthedocs.io/en/0.3.3/ on browserstack.com, and it still doesn't work on those old versions:

Windows/Firefox 32
Windows/Chrome 37
Windows/Opera 23


For comparison, https://nbsphinx.readthedocs.io/en/0.3.4/ works fine on all of them.

**Comment by benjaoming** [comment]
> For comparison, https://nbsphinx.readthedocs.io/en/0.3.4/ works fine on all of them.

That's an interesting comparison!

The most important difference is that 0.3.4 has:

```
<script type="text/javascript" src="https://nbsphinx.readthedocs.io/en/0.3.4/_static/js/theme.js"></script>
```

...which 0.3.3 (broken version) doesn't. It doesn't load any theme.js file.

It seems like both `readthedocs-doc-embed.js` and `theme.js` are defining `window.SphinxRtdTheme` so I wonder if it's because the version in `readthedocs-doc-embed.js` doesn't work.

We should figure out if this is the common denominator for all the botched versions.

#### Other notes

<details><summary>Details</summary>
<p>

Stuff that's the same:

* jQuery version
* readthedocs-doc-embed.js has same external URL
* the `.rst-versions` DOM element has an identical structure AFAICT

0.3.4 (working fine) has this call at the end of its `<body>`:

```
SphinxRtdTheme.Navigation.enable(true);
```

0.3.3 has this:

```
SphinxRtdTheme.Navigation.enableSticky();
```

I don't know the difference but calling `SphinxRtdTheme.Navigation.enable(true)` on 0.3.3 doesn't work, neither.

</p>
</details>

**Comment by saleh-unikie** [comment]
I can see this problem after adding the `.readthedocs.yaml` file to the project. Before adding this file, the project was working fine, but after that, the flyout menu stopped working.

This is the content of the config file:
```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: doc/conf.py

formats:
  - pdf
  - htmlzip
```

How it can affect on the JS related functionalities?

**Comment by humitos** [comment]
@saleh-unikie can you please open a new issue for your problem? This one is about old doc versions.

**Comment by humitos** [comment]
I think the new implementation of the `addons.js` could:

- remove all the old broken integration (`https://media.readthedocs.org/javascript/readthedocs-doc-embed.js`, `https://media.readthedocs.org/javascript/readthedocs-analytics.js`, `https://media.readthedocs.org/css/readthedocs-doc-embed.css`, `_static/readthedocs-data.js`) using the same technique we are currently using
- inject the new addons integration

This way, we will keep old version working fine without rebuilding or touching the HTML at all. cc @ericholscher what do you think about this idea for once we have deployed the new addons more broadly?

**Comment by humitos** [comment]
> This way, we will keep old version working fine without rebuilding or touching the HTML at all. cc @ericholscher what do you think about this idea for once we have deployed the new addons more broadly?

I've already implemented this in https://github.com/readthedocs/readthedocs-ops/pull/1402 and I'm currently testing it on our `test-builds` project: https://test-builds.readthedocs.io/en/latest/. That URL uses the new flyout (bottom right) and removes the old flyout (integrated in the navbar at bottom left). So far, it's working great 🚀

**Comment by humitos** [comment]
I also opened an issue at https://github.com/readthedocs/ext-theme/issues/212 to discuss the possibility to let people opt-in into the new addons (new flyout, new search as you type, and others) and also fix their old using this process. I'd appreciate feedback on that to know if people is interested.

**Comment by mgeier** [comment]
I don't understand: will the "new flyout" replace the old integrated flyout even on old, already built page versions?

How can an author "opt in" to something without re-building all their old stuff?

I thought the idea was that old builds will just remain as they were.

AFAIU, this issue is about fixing the JS in already existing builds, not about new builds.

> our `test-builds` project: https://test-builds.readthedocs.io/en/latest/. That URL uses the new flyout (bottom right) and removes the old flyout (integrated in the navbar at bottom left). So far, it's working great 🚀

It is working, but the content is not scrollable (see  #7375). When I open the flyout on my small laptop screen, the top of it is out of view, so I cannot close it again.

**Comment by humitos** [comment]
> I don't understand: will the "new flyout" replace the old integrated flyout even on old, already built page versions?

Yes, but not by default. At least right now. We are still in beta and testing it only on projects using "build.commands" only for now.

> How can an author "opt in" to something without re-building all their old stuff?

We think we will add an option on the project's setting for this. We are working on it to expand the usage of the new addons (including the flyout), but we haven't finished this work yet.

Would you be interesting on give it a try on your projects when it's ready? Or even before that? (we have a way to enable it by request)

> It is working, but the content is not scrollable (see #7375). When I open the flyout on my small laptop screen, the top of it is out of view, so I cannot close it again.

Yes. This is a bug in the current flyout addons we have already reported and we need to fix.

**Comment by humitos** [comment]
@mgeier 

> It is working, but the content is not scrollable (see #7375). When I open the flyout on my small laptop screen, the top of it is out of view, so I cannot close it again.

This issue is solved in the new flyout and it will release/deployed soon. Besides, we added an event listener that when clicking outside the flyout it also closes it. See https://github.com/readthedocs/addons/pull/129

**Comment by humitos** [comment]
I think we can close this issue since the problem is solved when enabling the new beta addons on the project. You can enable them by:

1. Opening https://beta.readthedocs.org
2. Going to the project's admin page
3. Clicking on Addons (Beta)
4. Checking the check-box
5. Save

Screenshot:

![Screenshot_2023-11-07_11-49-56](https://github.com/readthedocs/readthedocs.org/assets/244656/6227dd7e-0213-4d46-9d2c-fd1ead81b9ea)


Feel free to enable the beta addons and let me know if that solves the problem on your projects. I'm happy to re-open the issue if this is not solved after enabling the beta addons. Eventually, the beta addons will be enabled by default in all the projects.

**Comment by mgeier** [comment]
I wouldn't consider this solved, since this needs intervention by project maintainers.

Many old pages are unmaintained (but still useful to readers), and those are still broken.

**Comment by humitos** [comment]
I understand. I'm not sure what we could do to fix issues on unmaintained projects. There is a solution already, but it requires maintainers to enable new beta addons or to re-build their project with newer dependencies.

**Comment by mgeier** [comment]
> I'm not sure what we could do to fix issues on unmaintained projects.

I don't know either.
But it *did* work in the past, so there *must* be something you can do from your side without intervention for individual project maintainers.

Breaking those old pages damages the trust in the service RTD provides, at least it does for me.
(of course I'm not entitled to anything, since I'm using the free tier)

**Comment by humitos** [comment]
Currently, we are in a transition. Read the Docs Addons is in beta at the moment and we can't enforce projects to use it, and that's why we are giving users the ability to opt-in to give it a try. The beta Read the Docs Addons will eventually replace the old integration when it gets more mature.

Enforcing using the Read the Docs Addons while they are in beta on all old projects is a big risk and we want to avoid it for now until we are sure it's going to work for most of the projects.

**Comment by mgeier** [comment]
> The beta Read the Docs Addons will eventually replace the old integration when it gets more mature.

What does "replace the old integration" mean exactly?
Will it "throw away the old integration and replace it with the generic bottom right badge"?
Or will it "restore the original functionality" somehow?
Or something else?
